server.port=8081
spring.application.name=customer-service

# Connexion Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Configuration PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/db_delivery_customer
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Config Swagger
springdoc.api-docs.path=/api-docs

# --- CONFIGURATION ZIPKIN / MICROMETER ---

# On veut tracer 100% des requetes (pour la demo)
management.tracing.sampling.probability=1.0

# L URL du serveur Zipkin (nom du conteneur docker 'zipkin')
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans

# Activer l export
management.endpoints.web.exposure.include=health,info,prometheus